baseURL: 'http://example.org/'
languageCode: en-us
title: We Are Cetragore
build:
  writeStats: true
menus:
  main:
    - identifier: home
      url: /
      name: Home
      weight: 1
    - identifier: about
      url: /about/
      name: About
      weight: 2
    - identifier: merch
      url: "https://www.facebook.com/799535320424442/shop/all_products?sort_type=recency&on_sale=false&in_stock=false&ref_code=mini_shop_profile_plus_shop_tab_cta&ref_surface=mini_shop_product_details"
      name: Merch
      weight: 3
      params:
        target: _blank
params:
  socials:
    - url: 'https://www.facebook.com/CETRAGORE'
      name: Facebook
      icon: fab fa-facebook
    - url: 'https://twitter.com/cetragore'
      name: Twitter
      icon: fab fa-twitter
    - url: 'https://instagram.com/cetragore'
      name: Instagram
      icon: fab fa-instagram
